### PR TITLE
[Refactoring] Style fix, more comments in client.c, and some renaming.

### PR DESCRIPTION
**Pull request by JDong820**
Someone forgot to run make format. Also refactored client.c for better understand-ability.

### CODE REVIEW

**Comment by SrsBusiness** [comment]
Can't we rename callbacker to something like listener?

**Comment by JDong820** [comment]
I wanted it to be very clear that callbackers and callback_executors are related. If we have listeners, what do I name the associated execution functions?

**Comment by SrsBusiness** [comment]
The purpose of callbacker is to listen for incoming packets and then push it onto a queue right? Maybe a name like callback_listener would be better?

**Comment by JDong820** [comment]
Good idea. Implemented.

**Comment by SrsBusiness** [comment]
looks good to merge then

**Pull request merged**
