### PR TITLE
Added basic error handling.

### PR DESCRIPTION
**Pull request by JDongian**
Fully working mock. May need restructuring before merge. Probably want more coverage too. Discuss design issues at #38.

### CODE REVIEW

**Comment by JDong820** [comment]
Previous version: https://github.com/NosotrosNueces/mcc/blob/aba051523d5ac98d96e856f865983b496968d820/sample/exceptions.h

**Comment by JDong820** [comment]
@amlweems please comment (restate) why this wasn't approved.

**Comment by JDongian** [comment]
Bump @amlweems

**Comment by JDongian** [comment]
ded

**Pull request closed without merging**
