### PR TITLE
Another Big Request

### PR DESCRIPTION
**Pull request by SrsBusiness**
Major changes:
Callback handlers do not have the same prototype 
```c
void f(bot_t * bot, void *data)
```
anymore. Now they each have their own, like
```c
void join_game(bot_t *bot, int32_t, uint8_t, int8_t, uint8_t, uint8_t, char *)
```
Consequently, there are now separate functions for registering each callback. This gives us better type safety (implying we had it to begin with).

Additionally now there's another function called packet_callback in client.c that executes the callbacks based on the packet id.

There's a lot of code, but we'll be better for it.

### CODE REVIEW

**Comment by SrsBusiness** [comment]
The cs lab machines don't have astyle, so I couldn't make format.

**Comment by JDong820** [comment]
Ran astyle.

**Comment by JDong820** [comment]
what do you think of adding a 'default_' prefix to all the functions in handers.c?

**Comment by JDong820** [comment]
Hey, this looks good, but I want you to respond to the name change request @SrsBusiness.

**Comment by SrsBusiness** [comment]
bump

**Comment by SrsBusiness** [comment]
Yeah let's add the "default_" prefix

**Comment by JDongian** [comment]
Fixed sample_defender to use the new api. What do you thing of `mcc_` as the prefix? I think it is more descriptive, shorter, and thus better.

**Comment by SrsBusiness** [comment]
Do you mean as an alternative to "default_"? Was there a reason for calling this project mcc? I thought it was just a pun on gcc.

**Comment by SrsBusiness** [comment]
Fixed original comment, half of it was redundant

**Comment by JDongian** [comment]
Yea, I think `mcc_` would be better than `default_` as a prefix. The project is called mcc because gcc, and we backronym'd it as the MineCraft C API.

**Comment by SrsBusiness** [comment]
The old "register_event" function is deprecated and will not work with the new code.

**Pull request merged**
